titantimes/valor

commands/avg.py

I have no idea if this works since I can't test it and it is made under the assumption that `guilds` is a list of strings so do test it before merging.

adaptive spacing in avg

---

commands/up.py

Sort by soul point shortcut

---

commands/uniform.py

Yeah, I removed the overlay option and made it so it does overlay by default if there isn't a color option.
Also made it compatible with older skins.
I just hope that nothing breaks.

Made overlay default and also fixes

---

commands/uniform.py
listeners/msg_listener.py
listeners/react_listener.py

I did this on phone so read through the changes first.

Check for id before sending confirmation message

---

commands/ffa.py

Just minor changes made on phone :skull:

Add the message after -ffa so it shows up on ping

---

cron/__init__.py
main.py
util/profile_calc.py

tested and works, should work on the main bot if snazz didn't put the wrong id for roles.

Auto gxp roles

---

commands/sus.py

Means vipplus will not be considered no rank !

Fixes wynn changing vip+ to vipplus

---

commands/map.py

no more .cf, .info; surely thats all it is right!

Changed avicia link in map.py

---

commands/__init__.py
commands/guild.py
util/valor_message.py

-guild (prefix)
Tested with multiple guild. If you can find more bugs, feel free to ping me on them, I will look into fixing it.

Guild overview command (-guild)

---

commands/guild.py

Fully tested, it should work now

Fix -guild command again

---

commands/guild.py

Add alias so you can run -g as well, it is a faster shorthand and makes it easier to run the command quickly

Add -guild alias, -g

---

commands/sus.py

Revert "Update sus.py"

---

commands/completion.py

Might want to check I've correctly added the decorators for valor commands

Added the completion command

---

commands/sus.py
commands/warcount.py

Added an error message for if the rows on someone turn up empty rather than returning nothing

warcount no return error

---

commands/HQ.py
commands/__init__.py

Added decorators and registered to __init__ too this time

Added HQ command

---

commands/completion.py

Added an overall % and removed some clutter

Completion.py overall

---

commands/sus.py

Checks if uuid is in blacklist table if it is makes the embed red and adds an alert, (the thing we was doing in valour testing)

Added blacklist warning to sus.py

---

util/profile_calc.py

updated to reflect inflated guild xp gains

Changed xp_rank values

---

commands/avg.py
commands/completion.py
commands/plot2.py

365 day maximum I assume the .env has the COUNCILD in it as the template one did that raw gave;

Added maximum days to queries on -avg and -plot2

---

mp/plot_process.py

added clips to stop the graph from smoothing into negative from long 0 strings

Updated plot_process.py

---

commands/avg.py
commands/plot2.py

Gave default values to my new variables so the command doesnt fail when no timeframe is given

Fixed plot2/avg bug

---

commands/history.py

I've tested everything I can think of for it, I think it's good to go it is a headache though I must have spent billions of hours on this now.

Complete -history re-write

---

commands/history.py

Added a merger for when there are silly duplicates of joins n such (just makes it so guild changes within the same hour are 1 entry)

History merger

---

commands/avg.py
commands/plot2.py

Fixed plot2/avg COUNCILID

---

commands/warcount.py

changed -t to be -w to match graids
added the range line at the bottom to match graids

Consistency changes

---

commands/sus.py

Fixes the blacklist not sending problem, it's literally just because it uses discord.red as a colour lol

Update sus.py fixes blacklisted players not showing up

---

commands/__init__.py
commands/graids.py
commands/lootpool.py
commands/map.py
commands/map_old.py

Rewrote -map, fixed bug with conn rendering.
Fixed small bug with -graids where the format type for the code block was showing
Wrote a new lootpool command! (I saw people asking about the lootpool so I thought I'd make it easier for them)

-map rewrite, -lootpool command and bug fix

---

assets/terr_conns.json
commands/map.py
commands/sus.py

- Fixed -sus crashing when player hadn't logged into hypixel
- Fixed -map bug that made it crash during start of seasons and off season
- Fixes for some broken territory connections in -map
Also added -g and -z options back to -map, just like the old one

Few bug fixes and -map overhaul completion

---

commands/sus.py

mojang api down for 20 hours now good idea to add backup api i thought
also forgot to change branch 😄

backup api for sus 

---

commands/warcount.py

set it to be guild aggregation following the logic the rest of the command does

Fixed -w param
